### PR TITLE
Added support for Laravel 5.6

### PR DESCRIPTION
**Pull request by duxthefux**

### CODE REVIEW

**Comment by Skysplit** [comment]
Thanks for the PR! Are you sure this is all that Laravel 5.6 needs?
I didn't maintain this package for awhile because I had no fun in fixing API breaking-changes (that came from laravel) in framework minor version updates.

Since laravel introduced `Rules` classes as way of defining validation rules, this might be an obstacle.

**Comment by duxthefux** [comment]
hey, i'm developing with it since yesterday and didn't have any issues. I can investigate a little ini there. What `Rules` classes do you? So which spots should I check?

**Comment by Skysplit** [comment]
I meant syntax like described here: https://laravel.com/docs/5.6/validation#rule-unique
Specifically:
```
Rule::unique('users')->ignore($user->id)
```

Edit: Also, in relation to your commits, I think PHP version (in composer.json and travis.yml) should be bumped as well (travis fails)

**Comment by duxthefux** [comment]
hey, checkout the latest changes. deleted a lot and used stock laravel stuff. Whole source folder is now down to ~220 lines of code.

**Comment by duxthefux** [comment]
are you sure to merge it into `2.0`. Would it make sense to make `3.0` or let the master have the latest version?

**Comment by Skysplit** [comment]
You can just merge to master, I'll do another branch out of that

**Comment by duxthefux** [comment]
ok. great. CI is still failing. any idea?

**Comment by Skysplit** [comment]
I'll take care of that sometime soon

wt., 5 cze 2018 o 17:33 duxthefux <notifications@github.com> napisał(a):

**Comment by duxthefux** [comment]
Ok but I cant merge. You have to do that :-)

**Comment by duxthefux** [comment]
hey, would you mind merging?

**Comment by duxthefux** [comment]
ping

**Comment by duxthefux** [comment]
anyone there?

**Pull request closed without merging**
