### PR TITLE
Added support for Laravel 7

### PR DESCRIPTION
**Pull request by duxthefux**

### CODE REVIEW

**Comment by Skysplit** [comment]
@duxthefux Hi there! Sorry for no responses on previous PRs.

Would you be interested in taking over the package?

I haven't been using PHP for 3 years, so I think it would be better if I migrate repository ownership to someone else.

Cheers!

**Comment by duxthefux** [comment]
@Skysplit hey, no worries. Thanks for the awesome package!

Yeah sure, I can take it over so it will be continued.

Best

**Comment by Skysplit** [comment]
@duxthefux I tried to transfer ownership but you already have that repository in your namespace. You can delete it/rename it -> after that I will transfer ownership.

**Comment by duxthefux** [comment]
UPDATED:
@Skysplit I think we have to make it more staged, as we have my fork in production and it would break.

My suggestion would be to merge this laravel 6 pull request (https://github.com/Skysplit/laravel5-intl-translation/pull/8). This is well tested in production.
 Then create a new release tag, then we can use your repo again (not my fork) and pin this new version. Then I can delete the fork and you can transfer the owner ship. 

What do you think?

Btw: If ownership is transferred, will it get a different name `duxthefux/laravel5-intl-transaction`? So, do you know if this will this break existing composer dependencies?

**Comment by Skysplit** [comment]
I added you as collaborator, so I think you can read/write repository now.
As for packagist - currently namespace uses my packagist account, so after transfer it will probably break.
In the end, you can have `skysplit/*`  version for older laravel and yours for newer ones.

**Comment by duxthefux** [comment]
Lets leave it as a collaborator now. Would that be ok for you?

**Comment by Skysplit** [comment]
Sure, of course! Let me know if you need something from "project owner" side

**Pull request closed without merging**
